### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_gamma

# 网站 URL ，最后勿加入斜杠
url: http://www.ynkmqnn.com

# 网站名称
name: 云南昆明销售中心

# 默认标题
title: 全能保险柜云南昆明办事处-昆明保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 昆明保险柜

# 版权，请改备案号
copy: 版权所有 &copy; 1999-2013 广东安能保险柜制造有限公司 <a href="http://www.miitbeian.gov.cn/" target="_blank">粤ICP备12015444号-20</a>

# 自定首页公司简介段落
# homepage_about: |
#   全能保险柜是以从事保险柜（箱）等安防产品为主的现代化保险柜...

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
# about: |
#   广东安能保险柜制造有限公司是...

#   公司控股工业集团创始于1935年...

#   经过多年的持续发展，公司已跻身...


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://test.html9.com/images/alpha-banner01.jpg
    link:  /b-7348.html

  - image: http://test.html9.com/images/alpha-banner02.jpg
    link:  /f-2714cke.html

  - image: http://test.html9.com/images/alpha-banner03.jpg
    link:  /asafe.html

  - image: http://test.html9.com/images/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **销售网点**：昆明销售中心

      **联系人**：刘先生

      **电话**：0871-3839473

      **地址**：云南省昆明市盘龙区环城东路36号昆明理工大学新迎校区科技1号楼1楼铺面

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **销售网点**：五华销售中心   

      **联系人**：刘先生

      **电话**：0871-5420968

      **地址**：云南省昆明市五华区西昌路698号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **销售网点**：官渡销售中心

      **联系人**：刘先生

      **电话**：13987163238

      **地址**：云南省昆明市官渡区二环东路583号金马立交桥下



# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：云南省昆明市盘龙区环城东路36号昆明理工大学新迎校区科技1号楼1楼铺面
  
  联系人：刘先生
  
  联系电话：0871-3839473


# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：云南省昆明市盘龙区环城东路36号昆明理工大学新迎校区科技1号楼1楼铺面
  ###联系人：刘先生
  ###联系电话：0871-3839473

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 102.790704, 25.009390 # auto-updated

# 百度地图框内地址
addr: 地址：云南省昆明市盘龙区环城东路36号昆明理工大学新迎校区科技1号楼1楼铺面
