### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_gamma

# 网站 URL ，最后勿加入斜杠
url: http://www.tjqnn.com

# 网站名称
name: 天津办事处

# 默认标题
title: 全能保险柜天津办事处-天津保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 天津保险柜

# 备案号
beian: 粤ICP备12015444号-29

# 自定首页公司简介段落
# homepage_about: |
#   全能保险柜是以从事保险柜（箱）等安防产品为主的现代化保险柜...

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
# about: |
#   广东安能保险柜制造有限公司是...

#   公司控股工业集团创始于1935年...

#   经过多年的持续发展，公司已跻身...


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://stores.qnnimg.com/banners/alpha-banner05.jpg
    link:  /b-7348.html

  - image: http://stores.qnnimg.com/banners/alpha-banner06.jpg
    link:  /f-2714cke.html

  - image: http://stores.qnnimg.com/banners/alpha-banner07.jpg
    link:  /asafe.html

  - image: http://stores.qnnimg.com/banners/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：金海马家具世界

      **联系人**：李经理

      **电话**：13920496658

      **地址**：天津河东区津塘公路与十四经路交口

  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：塘沽大通文化用品

      **联系人**：李经理

      **电话**：13920496658

      **地址**：天津塘沽区营口道88号
      
  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：金街现代办公

      **联系人**：李经理

      **电话**：13920496658

      **地址**：天津塘沽区金街
      
  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：集美家居城

      **联系人**：李经理

      **电话**：13920496658

      **地址**：天津西青区卫津南路88号

  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：具多美家具城

      **联系人**：李经理

      **电话**：13920496658

      **地址**：天津武清区汽车总站旁
      
  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：大港滨江购物

      **联系人**：李经理

      **电话**：13920496658

      **地址**：天津大港区油田3号院
      
  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：金海马家具商城

      **联系人**：李经理

      **电话**：13920496658

      **地址**：天津南开区卫津路168号
      
  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：天津市金海马家具总汇

      **联系人**：杜刚

      **电话**：022-24462510

      **地址**：天津区狮子林大街（河北区政府对面）

  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：新中国商厦

      **联系人**：翟先生

      **电话**：022-27115769

      **地址**：天津区和平区和平路新中国商厦3楼

  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：欧迈办公用品

      **联系人**：郭先生

      **电话**：022-28134089

      **地址**：天津河西区黑牛城道谊城公寓8号


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：天津河东区津塘公路与十四经路交口
  
  联系人：李经理
  
  联系电话：13920496658
  
 
# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：天津河东区津塘公路与十四经路交口
  ###联系人：李经理
  ###联系电话：13920496658

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 117.200016, 39.131930 # auto-updated

# 百度地图框内地址
addr: 地址：天津河东区津塘公路与十四经路交口

# 右上角电话
telephone: 全能保险柜总部：400-830-4555
