### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_gamma

# 网站 URL ，最后勿加入斜杠
url: http://www.gxhzqnn.com

# 网站名称
name: 广西贺州销售中心

# 默认标题
title: 全能保险柜广西贺州销售中心-贺州保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 贺州保险柜

# 备案号
beian: 粤ICP备12015444号-

# 自定首页公司简介段落
# homepage_about: |
#   全能保险柜是以从事保险柜（箱）等安防产品为主的现代化保险柜...

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
# about: |
#   广东安能保险柜制造有限公司是...

#   公司控股工业集团创始于1935年...

#   经过多年的持续发展，公司已跻身...


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://stores.qnnimg.com/banners/alpha-banner05.jpg
    link:  /b-7348.html

  - image: http://stores.qnnimg.com/banners/alpha-banner06.jpg
    link:  /f-2714cke.html

  - image: http://stores.qnnimg.com/banners/alpha-banner07.jpg
    link:  /asafe.html

  - image: http://stores.qnnimg.com/banners/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：贺州销售中心

      **联系人**：黄江延

      **电话**：0774-5299388

      **地址**：广西省贺州市八步区前进西路42号（牛仔路口往老车站下50米）

  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：贺州销售中心

      **联系人**：黄江延

      **电话**：0774-5299388

      **地址**：广西省贺州市八步区建设中路33-1号（邮政银行旁边）

  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：贺州销售中心

      **联系人**：吴小惠

      **电话**：15676421388

      **地址**：广西省贺州市新兴北路（新现代家电城）

  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：贺州销售中心

      **联系人**：陈小燕

      **电话**：15676421313

      **地址**：广西省贺州市八步区向阳路恒兴花园一楼（三洋家电城)

  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：富川县销售中心

      **联系人**：黄江延

      **电话**：0774-7881288

      **地址**：广西省贺州市富川瑶族自治县凤凰路新华车站旁边（步行街路口）

  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：钟山县销售中心

      **联系人**：朱子杰

      **电话**：0774-8988983

      **地址**：广西省贺州市八步区钟山县老粮食局门面（土产局对面）

  - thumb: http://stores.qnnimg.com/photos/150px/qnnsafe01.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：昭平县销售中心

      **联系人**：陈文进

      **电话**：15278429212

      **地址**：广西省贺州市八步区昭平县河西东路89号（粮食局对面）


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：广西省贺州市八步区前进西路42号（牛仔路口往老车站下50米）
  
  联系人：黄江延
  
  联系电话：0774-5299388


# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：广西省贺州市八步区前进西路42号（牛仔路口往老车站下50米）
  ###联系人：黄江延
  ###联系电话：0774-5299388

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.28,22.76

# 百度地图框内地址
addr: 地址：广西省贺州市八步区前进西路42号（牛仔路口往老车站下50米）

# 右上角电话
telephone: 全能保险柜总部：400-830-4555
