### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_alpha

# 网站 URL ，最后勿加入斜杠
url: http://www.jzqnn.com.cn

# 网站名称
name: 荆州代理商

# 默认标题
title: 全能荆州代理商

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 保险柜,保险箱,家用保险柜,家用保险箱,保险柜十大品牌,全能保险柜

# 版权，请改备案号
copy: 版权所有 &copy; 1999-2013 广东安能保险柜制造有限公司 <a href="http://www.miibeian.gov.cn/" target="_blank">粤ICP备</a>

# 自定首页公司简介段落
# homepage_about: |
#   全能保险柜是以从事保险柜（箱）等安防产品为主的现代化保险柜...

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
# about: |
#   广东安能保险柜制造有限公司是...

#   公司控股工业集团创始于1935年...

#   经过多年的持续发展，公司已跻身...


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://www.qnnsafe.com/banner01.jpg
    link:  /b-7348.html

  - image: http://test.html9.com/images/alpha-banner02.jpg
    link:  /f-2714cke.html

  - image: http://test.html9.com/images/alpha-banner03.jpg
    link:  /asafe.html

  - image: http://test.html9.com/images/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a class="individual_qq" data-qq="519099098" href="#">客户咨询</a>
  <a class="individual_qq" data-qq="594745963" href="#">客户咨询</a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **销售网点**：荆州市全能旗舰店

      **联系人**：周丽

      **电话**：0716-8260199

      **地址**：湖北省荆州市北京西路文湖公园十字路

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **销售网点**：公安县全能旗舰店

      **联系人**：周丽

      **电话**：0716-5151898

      **地址**：湖北省荆州市公安县通运车站出站口对门

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **销售网点**：石首市全能旗舰店

      **联系人**：陈涛

      **电话**：0716-7280258

      **地址**：湖北省石首市中山路183#科技馆旁

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **销售网点**：松滋市全能旗舰店

      **联系人**：胡新财

      **电话**：0716-6267158

      **地址**：湖北省松滋市新江口大桥市标转盘处


# 侧栏联系（每行代码前加入两个空格）
contact: |
  **荆州旗舰店地址：**湖北省荆州市北京西路文湖公园十字路
  
  **传真咨询电话：**0716-8260199
  
  **加盟投诉热线：**13310599488（崔经理）
  
  **全国客服热线：**400-830-4555
  
  **售后服务电话：**13797508018
  
  **业务洽谈邮箱：**Qnbxgcdp@163.com 

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：湖北省荆州市北京西路文湖公园十字路
  ###联系人：崔经理
  ###联系电话：13310599488
  ###邮箱：Qnbxgcdp@163.com 

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 112.244432, 30.330196 # auto-updated

# 百度地图框内地址
addr: 地址：湖北省荆州市北京西路文湖公园十字路

# 右上角电话
telephone: <a href="http://www.qnn.com.cn/" target="_blank">全能保险柜总部</a> 400-830-4555
