### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_gamma

# 网站 URL ，最后勿加入斜杠
url: http://www.bjqnn.cn

# 网站名称
name: 北京办事处

# 默认标题
title: 全能北京办事处-北京保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 北京保险柜

# 备案号
beian: 粤ICP备12015444号-4

# 自定首页公司简介段落
# homepage_about: |
#   全能保险柜是以从事保险柜（箱）等安防产品为主的现代化保险柜...

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
# about: |
#   广东安能保险柜制造有限公司是...

#   公司控股工业集团创始于1935年...

#   经过多年的持续发展，公司已跻身...


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://test.html9.com/images/alpha-banner01.jpg
    link:  /b-7348.html

  - image: http://test.html9.com/images/alpha-banner02.jpg
    link:  /f-2714cke.html

  - image: http://test.html9.com/images/alpha-banner03.jpg
    link:  /asafe.html

  - image: http://test.html9.com/images/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市昌平区东小口镇合立方中滩六号院一号楼409室

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市昌平区东小口镇合立方中滩六号院一号楼409室

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市朝阳区亚奥北苑路甲13号办公用品区

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市西城区复兴门外大街15号B1层办公用品区

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市朝阳区成寿寺路308号主楼西区415号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市海淀区翠微路5号翠微大厦5层

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市昌平区立汤路186号龙德广场四层办公用品区 

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市海淀区花园路2号办公用品区

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市海淀区清河嘉园东区甲1号(近清河新城)办公用品区

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市海淀区中关村大街40号当代商城B1楼

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市海淀区北沙滩1号院35号楼地下二层

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市朝阳区东四环中路191号家居馆B1层/建材馆3层

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市海淀区阜成路68号集美2层办公区

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市海淀区远大路1号办公用品区

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市朝阳区北四环东路65号五金超市内

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市海淀区远大路1号金源时代购物中心五金超市内

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市丰台区西三环南路甲27号五金超市内

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市朝阳区十八里店大洋坊路106号五金超市内

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市丰台区南三环西路58号五金超市内

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-52003228

      **地址**：北京市朝阳区曙光西路206号（三元西桥向北500米路西，国际村南门）

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市海淀区北三环西路38号办公用品区

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市西城区西单北大街120号办公用品区

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：王经理

      **电话**：010-84943881

      **地址**：北京市朝阳区亮马桥路50号办公用品区


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：北京市昌平区东小口镇合立方中滩六号院一号楼409室
  
  联系人：王经理
  
  联系电话：010-84943881
  

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：北京市昌平区东小口镇合立方中滩六号院一号楼409室
  ###联系人：王经理
  ###联系电话：010-84943881

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 116.423400, 40.038403 # auto-updated

# 百度地图框内地址
addr: 地址：北京市昌平区东小口镇合立方中滩六号院一号楼409室
