### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_gamma

# 网站 URL ，最后勿加入斜杠
url: http://www.gzqnn.com

# 网站名称
name: 广东广州办事处

# 默认标题
title: 全能保险柜广东广州办事处-广州保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 广州保险柜

# 备案号
beian: 粤ICP备12015444号-2

# 自定首页公司简介段落
homepage_about: |
  广州市海珠区帛澳保险柜经营部是以从事保险柜（箱）等安防产品为主的现代化保险柜，拥有占地面积33000平方米的现代化厂房，装备了数百台国际著名品牌的数控冲床、折弯机、激光切割机、以及弧焊机器人等设备，并配备了独立的研发中心、检测中心、寿命实验室，具有世界领先的制造设备和工艺流程，产品涉及家用保险柜、文件保密柜、酒店客房保险箱、枪弹柜、金库门等多个系列近300余款产品，年生产规模超过30万台。

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
about: |
  广州市海珠区帛澳保险柜经营部是以从事保险柜（箱）等安防产品为主的现代化企业，总部公司拥有占地面积33000平方米的现代化厂房，装备了数百台国际著名品牌的数控冲床、折弯机、激光切割机、以及弧焊机器人等设备，并配备了独立的研发中心、检测中心、寿命实验室，具有世界领先的制造设备和工艺流程，产品涉及家用保险柜、文件保密柜、酒店客房保险箱、枪弹柜、金库门等多个系列近300余款产品，年生产规模超过30万台。

  总部公司控股工业集团创始于1935年，保险柜的制造历史可追溯到1939年，其间经历了中国现代工业的历史变迁，上世纪九十年代恢复了保险柜的生产，1999年广东安能保险柜制造有限公司正式成立，旗下“全能”品牌是中国保险柜行业的旗舰品牌。在公司的发展过程中，受到了社会的普遍认同，相继获得广东省著名商标、高新技术企业、中国保险柜十大品牌、中国酒店用品十大品牌、中国家具最受消费者欢迎品牌等荣誉称号，公司同时是中国安防协会理事单位、广东省安防协会理事单位。

  经过多年的持续发展，公司已跻身为中国大陆领先、华南地区产销量第一的保险柜制造企业，创新的技术研发、卓越的品质控制、完善的售后服务，成为了北京奥运会、上海世博会、广州亚运会产品供应商，同时为中国移动、中国石油、中国银行等大型国企及公安部门、武警部队等军政部门提供各类专业保险柜产品。

  时至今日，全能产品已遍布全国各省、自治区、直辖市，形成了以2000余个销售网点、300余家专卖店为主力的强大营销网络，有超过500万以上的忠实用户。产品远销中东、欧美、非洲、南太平洋等几十个国家和地区，并获得欧盟CE及ROHS等多项国际权威认证，成为多个国际名牌的OEM供应商，是国内最知名的保险柜出口品牌之一。

  立足当下，壮志满怀，展望未来，意气风发。在不断探索创新中，诚信、智慧的全能人，正在努力打造中国安防行业的航空母舰，向服务全球的国际性综合安防集团企业迈进！


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://stores.qnnimg.com/billboards/alpha-billboard-05.jpg
    link:  /b-7348.html

  - image: http://stores.qnnimg.com/billboards/alpha-billboard-06.jpg
    link:  /f-2714cke.html

  - image: http://stores.qnnimg.com/billboards/alpha-billboard-07.jpg
    link:  /asafe.html

  - image: http://stores.qnnimg.com/billboards/alpha-billboard-04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=904381538&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:904381538:41" alt="点击这里给我发消息" title="点击这里给我发消息"/></a>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=200802811&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:904381538:41" alt="点击这里给我发消息" title="点击这里给我发消息"/></a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：广州办事处

      **联系人**：王小姐

      **电话**：020-84224868

      **地址**：广东省广州市海珠区赤岗西路328号

  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：海珠专卖店

      **联系人**：李小姐

      **电话**：020-84266211

      **地址**：广东省广州市海珠区江南大道南411号

  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：黄埔专卖店

      **联系人**：冯小姐

      **电话**：020-82276997

      **地址**：广东省广州市黄埔区黄埔东路47-49号

  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：越秀专卖店

      **联系人**：王小姐

      **电话**：15818188103

      **地址**：广东省广州市越秀区东风东路532号

  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：天河正佳店

      **联系人**：李小姐

      **电话**：020-84266211

      **地址**：广东省广州市天河区正佳广场三楼友谊商场

  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：天河正佳店

      **联系人**：王小姐

      **电话**：020-84224868

      **地址**：广东省广州市海珠区赤岗西路328号消防器材厂内


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：广东省广州市越秀区东风东路532号
  
  联系人：王小姐
  
  联系电话：020-84224868

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：广东省广州市越秀区东风东路532号
  ###联系人：王小姐
  ###联系电话：020-84224868

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.28,22.76

# 百度地图框内地址
addr: 地址：广东省广州市越秀区东风东路532号

# 右上角电话
telephone: 广州办事处：020-84224868
