### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_gamma

# 网站 URL ，最后勿加入斜杠
url: http://www.sxxaqnn.com

# 网站名称
name: 陕西西安销售中心

# 默认标题
title: 全能保险柜陕西西安销售中心-西安保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 西安保险箱

# 备案号
beian: 粤ICP备12015444号-9

# 自定首页公司简介段落
# homepage_about: |
#   全能保险柜是以从事保险柜（箱）等安防产品为主的现代化保险柜...

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
# about: |
#   广东安能保险柜制造有限公司是...

#   公司控股工业集团创始于1935年...

#   经过多年的持续发展，公司已跻身...


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://stores.qnnimg.com/billboards/alpha-billboard-05.jpg
    link:  /b-7348.html

  - image: http://stores.qnnimg.com/billboards/alpha-billboard-06.jpg
    link:  /f-2714cke.html

  - image: http://stores.qnnimg.com/billboards/alpha-billboard-07.jpg
    link:  /asafe.html

  - image: http://stores.qnnimg.com/billboards/alpha-billboard-04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>高新旗舰店</p>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2019311099&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:2019311099:41" alt="点击这里给我发消息" title="点击这里给我发消息"/></a>
  <p>曲江精品店</p>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2726332306&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:2726332306:41" alt="点击这里给我发消息" title="点击这里给我发消息"/></a>
  <p>明德门专卖店</p>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2020228096&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:2020228096:41" alt="点击这里给我发消息" title="点击这里给我发消息"/></a>

# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://www.qnnsafe.com/stores01.jpg
    photo: http://www.qnnsafe.com/stores01.jpg
    content: |
      **销售网点**：西安高新区销售中心

      **联系人**：王先生

      **电话**：029-88193958

      **地址**：陕西省西安市高新区科技路枫叶新都市B5-1101号

  - thumb: http://www.qnnsafe.com/stores02.jpg
    photo: http://www.qnnsafe.com/stores02.jpg
    content: |
      **销售网点**：西安雁塔区销售中心

      **联系人**：王先生

      **电话**：029-85499960

      **地址**：陕西省西安市雁塔区朱雀大街南段伟丰花园西门向南50米

  - thumb: http://www.qnnsafe.com/stores03.jpg
    photo: http://www.qnnsafe.com/stores03.jpg
    content: |
      **销售网点**：西安曲江新区销售中心

      **联系人**：王先生

      **电话**：029-89131761

      **地址**：陕西省西安市曲江新区芙蓉东路69号中海东郡西门向南50米路东


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：陕西省西安市高新区科技路枫叶新都市B5-1101号
  
  联系人：王女士
  
  电话：029-85499960
  

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：陕西省西安市西安市高新区科技路枫叶新都市B5-1101号
  ###联系人：王先生
  ###联系电话：029-85499960

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.28,22.76

# 百度地图框内地址
addr: 地址：陕西省西安市高新区科技路枫叶新都市B5-1101号

# 右上角电话
telephone: 全能保险柜总部：400-830-4555
