### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_gamma

# 网站 URL ，最后勿加入斜杠
url: http://www.jsczqnn.com

# 网站名称
name: 江苏常州办事处

# 默认标题
title: 全能江苏常州办事处-常州保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 常州保险柜

# 备案号
beian: 粤ICP备12015444号-26

# 自定首页公司简介段落
# homepage_about: |
#   全能保险柜是以从事保险柜（箱）等安防产品为主的现代化保险柜...

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
# about: |
#   广东安能保险柜制造有限公司是...

#   公司控股工业集团创始于1935年...

#   经过多年的持续发展，公司已跻身...


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://stores.qnnimg.com/banners/alpha-banner05.jpg
    link:  /b-7348.html

  - image: http://stores.qnnimg.com/banners/alpha-banner06.jpg
    link:  /f-2714cke.html

  - image: http://stores.qnnimg.com/banners/alpha-banner07.jpg
    link:  /asafe.html

  - image: http://stores.qnnimg.com/banners/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **联系人**：张先生

      **电话**：13511674355

      **地址**：江苏常州市勤业路五星乡政府对面


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：江苏常州市勤业路五星乡政府对面
  
  联系人：张先生
  
  联系电话：13511674355

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：江苏常州市勤业路五星乡政府对面
  ###联系人：张先生
  ###联系电话：13511674355

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 119.941557, 31.800895 # auto-updated

# 百度地图框内地址
addr: 地址：江苏常州市勤业路五星乡政府对面

# 右上角电话
telephone: 全能保险柜总部：400-830-4555
