### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_gamma

# 网站 URL ，最后勿加入斜杠
url: http://www.cqqnn.com

# 网站名称
name: 重庆销售中心

# 默认标题
title: 全能保险柜重庆销售中心-重庆保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 重庆保险柜

# 备案号
beian: 粤ICP备12015444号-30

# 自定首页公司简介段落
homepage_about: |
  渝北区渝力保险柜经营部是以从事保险柜（箱）等安防产品为主的现代化保险柜，拥有占地面积33000平方米的现代化厂房，装备了数百台国际著名品牌的数控冲床、折弯机、激光切割机、以及弧焊机器人等设备，并配备了独立的研发中心、检测中心、寿命实验室，具有世界领先的制造设备和工艺流程，产品涉及家用保险柜、文件保密柜、酒店客房保险箱、枪弹柜、金库门等多个系列近300余款产品，年生产规模超过30万台。

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
about: |
  渝北区渝力保险柜经营部是以从事保险柜（箱）等安防产品为主的现代化企业，总部公司拥有占地面积33000平方米的现代化厂房，装备了数百台国际著名品牌的数控冲床、折弯机、激光切割机、以及弧焊机器人等设备，并配备了独立的研发中心、检测中心、寿命实验室，具有世界领先的制造设备和工艺流程，产品涉及家用保险柜、文件保密柜、酒店客房保险箱、枪弹柜、金库门等多个系列近300余款产品，年生产规模超过30万台。

  总部公司控股工业集团创始于1935年，保险柜的制造历史可追溯到1939年，其间经历了中国现代工业的历史变迁，上世纪九十年代恢复了保险柜的生产，1999年广东安能保险柜制造有限公司正式成立，旗下“全能”品牌是中国保险柜行业的旗舰品牌。在公司的发展过程中，受到了社会的普遍认同，相继获得广东省著名商标、高新技术企业、中国保险柜十大品牌、中国酒店用品十大品牌、中国家具最受消费者欢迎品牌等荣誉称号，公司同时是中国安防协会理事单位、广东省安防协会理事单位。

  经过多年的持续发展，公司已跻身为中国大陆领先、华南地区产销量第一的保险柜制造企业，创新的技术研发、卓越的品质控制、完善的售后服务，成为了北京奥运会、上海世博会、广州亚运会产品供应商，同时为中国移动、中国石油、中国银行等大型国企及公安部门、武警部队等军政部门提供各类专业保险柜产品。
  
  时至今日，全能产品已遍布全国各省、自治区、直辖市，形成了以2000余个销售网点、300余家专卖店为主力的强大营销网络，有超过500万以上的忠实用户。产品远销中东、欧美、非洲、南太平洋等几十个国家和地区，并获得欧盟CE及ROHS等多项国际权威认证，成为多个国际名牌的OEM供应商，是国内最知名的保险柜出口品牌之一。

  立足当下，壮志满怀，展望未来，意气风发。在不断探索创新中，诚信、智慧的全能人，正在努力打造中国安防行业的航空母舰，向服务全球的国际性综合安防集团企业迈进！

# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://stores.qnnimg.com/billboards/alpha-billboard-05.jpg
    link:  /products/b-4538.html

  - image: http://stores.qnnimg.com/billboards/alpha-billboard-06.jpg
    link:  /products/bmg-8001ab.html

  - image: http://stores.qnnimg.com/billboards/alpha-billboard-07.jpg
    link:  /products/zf-4538br.html

  - image: http://stores.qnnimg.com/billboards/alpha-billboard-04.jpg
    link:  /products/fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=944310236&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:904381538:41" alt="点击这里给我发消息" title="点击这里给我发消息"/></a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：全能保险柜重庆销售中心

      **联系人**：文先生

      **电话**：023-65230832

      **地址**：重庆市沙坪坝新桥新村88号(新桥医院东)

  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：全能保险柜重庆专卖店

      **联系人**：文先生

      **电话**：023-65230832

      **地址**：重庆市渝北区回兴宝桐一路209号（3号轻轨回兴站西北角）
      
  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **销售网点**：全能保险柜重庆经销点

      **联系人**：陈先生

      **电话**：023-42731023

      **地址**：重庆市合川区南园西路538号(区府后门)


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：重庆市沙坪坝新桥新村88号(新桥医院东)
  
  联系人：文先生
  
  联系电话：023-65230832

# 联系页（每行代码前加入两个空格）中心
contacthtml: |
  ###地址：重庆市沙坪坝新桥新村88号(新桥医院东)
  ###联系人：文先生
  ###联系电话：023-65230832

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.28,22.76

# 百度地图框内地址
addr: 地址：重庆市沙坪坝新桥新村88号(新桥医院东)

# 右上角电话
telephone: 重庆销售中心电话：13996455099

# 自定各产品的淘宝链接，default是默认链接（可以填上店铺主页），产品用名称（name字段，如BW-6960）对应网址
taobao:
  default: http://www.taobao.com/
  B-4538: 
  B-5440: 
  B-7348: 
  BGX-2535: 
  BGX-5840: 
  BMG-7545A/B: 
  BMG-8001A/B: 
  BMG-8002A/B: 
  BMG-8003A/B: 
  BMG-9055A/B: 
  BP-6747: 
  BP-9050: 
  BW-6960: 
  CKI-253525: 
  CM-2045: 
  CM-2045ZH: 
  CS-2018D: 
  CS-2221D: 
  CS-2520C: 
  CS-4021C: 
  CT-1211: 
  CT-1211H: 
  CT-4013: 
  CT-4013ME: 
  CT-4013ZH: 
  CT-4018ZH: 
  CW-7348: 
  C型不带枪锁枪弹柜: 
  C型枪弹柜系列: 
  DG-6442DS: 
  DG-7645D: 
  DG-7645S: 
  DG-9150D: 
  DG-9150S: 
  DM-2146: 
  DM-2146ZH: 
  D型零头弹药柜: 
  ES-2045ZH: 
  ES-2318W: 
  E型部队专用携行枪柜: 
  F-1614C: 
  F-2014C/K/E: 
  F-2714C/K/E: 
  F-2720ICK: 
  F-2720ILK: 
  F-3020C/E: 
  F-3020CC/EE: 
  F-3214CC/EE: 
  F-3214CCM/EEM: 
  F-4020ILK: 
  FG-100B/R: 
  FG-11860B/R: 
  FG-153: 
  FG-15870B/R: 
  FG-2940B/R: 
  FG-3001: 
  FG-3002: 
  FG-3542B/R: 
  FG-5840B/R: 
  FG-6001: 
  FG-6002: 
  FG-6006: 
  FG-6024F: 
  FG-6030F: 
  FG-6842B/R: 
  FG-8045B/R: 
  FG-9150B/R: 
  FG-9150D: 
  FRD-21: 
  FRD-31: 
  FRD-42: 
  GLF-3340: 
  GLF-4540: 
  GLF-5842: 
  GLF-7042: 
  GLF-7550: 
  GLF-8550: 
  GTX-11860: 
  GTX-15870: 
  GTX-3345: 
  GTX-4542: 
  GTX-5842: 
  GTX-6845: 
  GTX-9050: 
  H-06: 
  H-12: 
  H-15: 
  HG-11860: 
  HG-15870: 
  HG-2740: 
  HG-3342: 
  HG-4538: 
  HG-5840: 
  HG-6842: 
  HG-7645D: 
  HG-8045: 
  HG-9150: 
  IF-1212SC: 
  IF-1500C: 
  IF-2500C: 
  IF-3000C: 
  ITG-2040: 
  ITG-3342: 
  ITG-5840: 
  JKM(B)-1020-N: 
  JKM(CS)-1020-N: 
  JKM(M)-1020-N: 
  KL-4045: 
  MA-2045ZH: 
  MB-2045UZH: 
  MF-2043ZH: 
  MG-2043ZH: 
  MG-2045: 
  MH-2043ZH: 
  MI-2045: 
  MI-2045UZH: 
  MK-2043ZH: 
  MQ-2045ZH: 
  QN-2043: 
  QN-2043ZH: 
  RH-1612K/C: 
  RH-2014C/K/E: 
  RH-2410C/K: 
  RH-3020CC: 
  SJB-1630B/R: 
  SJB-2243B/R: 
  SJB-3236B/R: 
  SJB-40HⅢB/R: 
  SJB-40ⅢB/R: 
  SJB-43ⅢB/R: 
  SJB-48ⅢB/R: 
  SJB-52ⅢB/R: 
  SJB-53ⅢB/R: 
  SJB-58ⅢB/R: 
  SJB-72ⅢB/R: 
  SJB-88ⅢB/R: 
  SJB-88ⅢDB/R: 
  SK-2045: 
  SK-2045ZH: 
  TGG-2040B/R: 
  TGG-2045B/R: 
  TGG-2740B/R: 
  TGG-3342B/R: 
  TGG-4538B/R: 
  TGG-4938B/R: 
  TGG-5840B/R: 
  TGG-6642B/R: 
  TGG-7645B/R: 
  US-1206K: 
  US-1C/K: 
  US-2C/K: 
  US-3C/K: 
  WS-108: 
  ZA-18090: 
  ZF-4538B/R: 
  ZF-4938B/R: 

