### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_gamma

# 网站 URL ，最后勿加入斜杠
url: http://www.gdfsqnn.com

# 网站名称
name: 广东佛山办事处

# 默认标题
title: 全能保险柜广东佛山办事处-佛山保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 佛山保险柜

# 备案号
beian: 粤ICP备12015444号-5

# 自定首页公司简介段落
# homepage_about: |
#   全能保险柜是以从事保险柜（箱）等安防产品为主的现代化保险柜...

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
# about: |
#   广东安能保险柜制造有限公司是...

#   公司控股工业集团创始于1935年...

#   经过多年的持续发展，公司已跻身...


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://test.html9.com/images/alpha-banner01.jpg
    link:  /b-7348.html

  - image: http://test.html9.com/images/alpha-banner02.jpg
    link:  /f-2714cke.html

  - image: http://test.html9.com/images/alpha-banner03.jpg
    link:  /asafe.html

  - image: http://test.html9.com/images/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：梁小姐

      **电话**：0757-86327085

      **地址**：广东省佛山市南海区桂城南海大道北92-11号（南海区政府左侧200米）

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：曾小姐

      **电话**：0757-83967109

      **地址**：广东省佛山市禅城区季华五路5号御景豪庭首层P1号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：余小姐

      **电话**：0757-81432098

      **地址**：广东省佛山市南海区黄岐黄海路37号怡富广场地铺192号（风度酒店对面）

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：胡小姐

      **电话**：0757-87740030

      **地址**：广东省佛山市三水区西南广海大道中27号（商业城）一区128号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：麦小姐

      **电话**：0757-88689662

      **地址**：广东省佛山市高明区沧江路241号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：宁小姐

      **电话**：0757-28106695

      **地址**：广东省佛山市顺德区乐从东恒家具城一排一座一号前仓（子材大桥往外国语学校方向100米）

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：周小姐

      **电话**：13679862350

      **地址**：广东省佛山市大良新桂中路康城花园尚域尚华苑106号


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：广东省佛山市南海区桂城南海大道北92-11号（南海区政府左侧200米）
  
  联系人：梁小姐
  
  联系电话：0757-86327085


# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：广东省佛山市南海区桂城南海大道北92-11号（南海区政府左侧200米）
  ###联系人：梁小姐
  ###联系电话：0757-86327085

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.111234, 23.018546 # auto-updated

# 百度地图框内地址
addr: 地址：广东省佛山市南海区桂城南海大道北92-11号（南海区政府左侧200米）
