layouts: _layout_gamma

# 网站 URL ，最后勿加入斜杠
url: http://www.gdswqnn.com

# 网站名称
name: 广东汕尾办事处

# 默认标题
title: 全能保险柜广东汕尾办事处-汕尾保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 汕尾保险柜

# 备案号
beian: 粤ICP备12015444号-22

# 自定首页公司简介段落
# homepage_about: |
#   全能保险柜是以从事保险柜（箱）等安防产品为主的现代化保险柜...

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
# about: |
#   广东安能保险柜制造有限公司是...

#   公司控股工业集团创始于1935年...

#   经过多年的持续发展，公司已跻身...


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://stores.qnnimg.com/billboards/alpha-billboard-05.jpg
    link:  /b-7348.html

  - image: http://stores.qnnimg.com/billboards/alpha-billboard-06.jpg
    link:  /f-2714cke.html

  - image: http://stores.qnnimg.com/billboards/alpha-billboard-07.jpg
    link:  /asafe.html

  - image: http://stores.qnnimg.com/billboards/alpha-billboard-04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **联系人**：黄新伟

      **电话**：18688079755

      **地址**：广东省汕尾市城区五马路御景园7栋11号

  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **联系人**：林坤洲

      **电话**：13502363846

      **地址**：广东省汕尾市陆丰陆城南堤路11号

  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **联系人**：潘先生

      **电话**：0660-6625029

      **地址**：广东省汕尾市海丰县城商业街天桥边

  - thumb: http://stores.qnnimg.com/photos/150px/default.jpg
    photo: http://stores.qnnimg.com/photos/default.jpg
    content: |
      **联系人**：叶先生

      **电话**：0660-3332977

      **地址**：广东省汕尾市大道中段友谊大厦


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：广东省汕尾市城区五马路御景园7栋11号
  
  联系人：黄新伟
  
  联系电话：18688079755
  

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：广东省汕尾市城区五马路御景园7栋11号
  ###联系人：黄新伟
  ###联系电话：18688079755

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 115.341936, 22.972594 # auto-updated

# 百度地图框内地址
addr: 地址：广东省汕尾市城区五马路御景园7栋11号

# 右上角电话
telephone: 全能保险柜总部：400-830-4555
