### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_gamma

# 网站 URL ，最后勿加入斜杠
url: http://www.scmyqnn.com

# 网站名称
name: 四川绵阳销售中心

# 默认标题
title: 全能保险柜四川绵阳销售中心-绵阳保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 绵阳保险柜

# 备案号
beian: 粤ICP备12015444号-

# 自定首页公司简介段落
# homepage_about: |
#   全能保险柜是以从事保险柜（箱）等安防产品为主的现代化保险柜...

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
# about: |
#   广东安能保险柜制造有限公司是...

#   公司控股工业集团创始于1935年...

#   经过多年的持续发展，公司已跻身...


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://stores.qnnimg.com/banners/alpha-banner05.jpg
    link:  /b-7348.html

  - image: http://stores.qnnimg.com/banners/alpha-banner06.jpg
    link:  /f-2714cke.html

  - image: http://stores.qnnimg.com/banners/alpha-banner07.jpg
    link:  /asafe.html

  - image: http://stores.qnnimg.com/banners/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **销售网点**：绵阳销售中心

      **联系人**：唐先生

      **电话**：0816-2228506

      **地址**：四川省绵阳市警钟街83号（原东街）

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **销售网点**：攀枝花销售中心

      **联系人**：李先生

      **电话**：0812-2828067

      **地址**：四川省攀枝花市东区五十四统一家私城斜对面远桦家私


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：四川省绵阳市警钟街83号（原东街）
  
  联系人：唐先生
  
  联系电话：0816-2228506

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：四川省绵阳市警钟街83号（原东街）
  ###联系人：唐先生
  ###联系电话：0816-2228506

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.28,22.76

# 百度地图框内地址
addr: 地址：四川省绵阳市警钟街83号（原东街）


